### ISSUE TITLE
new algorithms

### ISSUE THREAD

**Issue by lpatiny** [mljs/ml#1]
- Distance / similarity
  - Tanimoto
  - Tree similarity (check with Andres Castillo)
- SVM
- Regression
  - PLS-DA
  - PLSA
- PCA
- Neural network ?
  - input -> hidden -> output
- Clustering
  - k-means
  - hierarchical

**Comment by maasencioh** [comment]
I think that Tanimoto's is already implemented in [here!(https://github.com/mljs/distance/blob/master/src/dist/tanimoto.js) but I'm not sure.

**Comment by JeffersonH44** [comment]
Which is supposed to be the purpose of the PLSA algorithm here? I saw that is related with documents to determine if it belong to certain topic.

**Comment by maasencioh** [comment]
All where already done :sunglasses:
