### ISSUE TITLE
Way to reuse model saved and retrieved from JSON?

### ISSUE THREAD

**Issue by davekuntz** [mljs/ml#112]
Hello,

I am wondering if there is a way/can be added to reuse a model that has been generated, stored, and retrieved.  For instance, I have created a pls model object, stored it as JSON, and inserted it into a database.  When I retrieve the model object it says that "predict" is not a function.  I found a similar implementation at http://mlweb.loria.fr/demos/mljs-tutorial-storage.html for just SVM and kernel ridge regression.  I adjusted it so that I can store and retrieve my pls model perfectly, but the predict functionality is gone.

**Comment by targos** [comment]
Models that are serializable to JSON can be reloaded using the static `load` method on the class. For PLS, it is `PLS.load(json)`

**Comment by davekuntz** [comment]
Thanks targos!  Is there a static store method too?  I have been through documentation but haven't found it referenced.

**Comment by targos** [comment]
For which usage? We implement a `toJSON` method on the prototype that will be called by `JSON.stringify` automatically

**Comment by davekuntz** [comment]
When I use JSON.stringify, it returns the model object with the options but none of the training parameters, IE T,W, etc.

Example:

`var pls = new PLS(options);
y_pred = pls.predict(X);
console.log(pls); // Shows all model parameters
console.log(JSON.stringify(pls)); // Only shows options and a few other parameters`

**Comment by davekuntz** [comment]
I made it work by following the knn code, which was easier for me to understand.  As you said, all that is required is JSON.stringify to store and PLS.load to retrieve.  Thank you!
