### ISSUE TITLE
Transpiling ml-matrix to ES-5

### ISSUE THREAD

**Issue by rajasd27** [mljs/ml#146]
Hello, I am trying to transpile ml-matrix to es5 using babel and webpack but it is not getting transpiled. Can someone pl tell me why is it not getting transpiled?

**Comment by targos** [comment]
Maybe your `node_modules` directory is ignored by babel?

**Comment by rajasd27** [comment]
Nevermind, it worked. I added the @babel/preset-env and it worked. Thanks anyway.
