### ISSUE TITLE
Uncaught TypeError: PCA is not a constructor or PCA is not a function

### ISSUE THREAD

**Issue by maatspencer** [mljs/ml#168]
When running ml.js through the web browser without node.js using `<script src="https://www.lactame.com/lib/ml/4.0.0/ml.min.js"></script>` it is unclear how to initialize the global `ML` variable so that the library functions can be accessed?  Any help is greatly appreciated

**Comment by lpatiny** [comment]
ML is a global object in window and you can create an instance of pca using `new ML.PCA(matrix)`

For example:
```
const data=[
  [1,2,3],
  [2,3,4],
  [3,4,5],
]

const pca = new ML.PCA(data)

console.log(pca.getExplainedVariance());
```
