### ISSUE TITLE
Allow to make polynomial regression on matrix

### ISSUE THREAD

**Issue by lpatiny** [mljs/ml#26]
Get inspired:

http://imagejdocu.tudor.lu/doku.php?id=plugin:filter:fit_polynomial:start

Regression.multivariatePolynomial([[x1,x2,x3],[y1,y2,y3]], options);
options: {degree: 2}
Regression.polynomial2D(matrix, options);

Regression.polynomial2D(matrix, {background:[[x1,x2,x3],[y1,y2,y3], degree: 2]});

returns: (see other regressions)

degree2 : x^2 y^2 xy x y c

**Comment by maasencioh** [comment]
Moved to the projects list of proposals
