### ISSUE TITLE
move libraries into typescript 

### ISSUE THREAD

**Issue by rajeevkumarsharma** [mljs/ml#65]

**Comment by maasencioh** [comment]
Hello @rajeevkumarsharma, currently there's no priority into the typescript migration

**Comment by targos** [comment]
We do not use typescript, so it's unlikely that we would move the source code to typescript. However, if someone wants to do the work of creating typescript definitions, we could help with it.
I'm going to close this issue in favor of https://github.com/mljs/ml/issues/61
