### ISSUE TITLE
get inspired !

### ISSUE THREAD

**Issue by lpatiny** [mljs/ml#7]
http://orange.biolab.si/

**Comment by lpatiny** [comment]
http://googleresearch.blogspot.ch/

**Comment by targos** [comment]
test

**Comment by targos** [comment]
maybe there is some interesting material on http://icml.cc/2015/

**Comment by maasencioh** [comment]
This seems to be interesting too http://www.jmlr.org/

**Comment by targos** [comment]
https://en.wikipedia.org/wiki/Inductive_logic_programming

**Comment by targos** [comment]
A lot of resources are linked on this page: https://www.quora.com/What-are-some-good-resources-to-learn-about-data-science-case-studies-use-cases-and-white-papers-implemented-in-various-industries

**Comment by maasencioh** [comment]
Moved to the projects list of references
