### ISSUE TITLE
Updated ml npm package

### ISSUE THREAD

**Issue by yawetse** [mljs/ml#92]
Hi guys,

First of, I love the work and the modular approach to constructing this library.

When is the next planned semver release on NPM, a lot of the individual packages have been updated (like`ml-naivebayes`) and it would be great to have them rolled up into a package again.

Thanks,
Yaw

**Comment by targos** [comment]
Hi! I just published v3.0.0 of the package with an up to date version of all dependencies.
Beware that the way they are exposed changed significantly. Take a look at the readme to learn about the new structure.

**Comment by yawetse** [comment]
@targos thanks for updating the package! Is there a logical home for https://github.com/mljs/decision-tree-cart in the master npm package?

Thanks again for the awesome work!

**Comment by targos** [comment]
@yawetse not yet! I opened https://github.com/mljs/ml/pull/93 to add it

**Comment by targos** [comment]
Published v3.1.0 with ml-cart included
